### ISSUE TITLE
Change Language Title from "k-lang" to "ksm-lang"

### ISSUE THREAD

**Issue by Doreen-Onyango** [kh3rld/ksm-lang#19]
We need to update the title and references of our programming language from "k-lang" to "ksm-lang" to better reflect the .ksm file extension and improve branding consistency.

**Comment by kh3rld** [comment]
Hello @Doreen-Onyango 

Thanks for pointing that out! I've made the updates to change the title from "k-lang" to "ksm-lang" as you suggested.

Thanks for your help in improving the project!
